-- PostgreSQL baseline: the schema as the eight SQLite migrations left it
-- (git history has them), translated to Postgres types. Existing SQLite data
-- moves over with `memolang import-sqlite`.
--
-- Ids are GENERATED BY DEFAULT (not ALWAYS) so the import can keep existing
-- ids; it then moves each sequence past the highest one.

CREATE TABLE users (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email         TEXT        NOT NULL,
    password_hash TEXT        NOT NULL DEFAULT '',
    display_name  TEXT        NOT NULL DEFAULT '',
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Case-insensitive uniqueness without the citext extension, which not every
-- Postgres build ships. Emails are also stored lowercased (NormalizeEmail).
CREATE UNIQUE INDEX users_email_lower ON users (lower(email));

CREATE TABLE user_sessions (
    token      TEXT PRIMARY KEY,
    user_id    BIGINT      NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    expires_at TIMESTAMPTZ NOT NULL
);

CREATE INDEX user_sessions_user ON user_sessions(user_id);

CREATE TABLE decks (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT      NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    name       TEXT        NOT NULL,
    mode       TEXT        NOT NULL DEFAULT 'srs' CHECK (mode IN ('srs', 'linear')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX decks_user ON decks(user_id);

-- interval_days, not interval: INTERVAL is a Postgres type keyword.
CREATE TABLE cards (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    deck_id       BIGINT           NOT NULL REFERENCES decks(id) ON DELETE CASCADE,
    front         TEXT             NOT NULL,
    back          TEXT             NOT NULL,
    example       TEXT             NOT NULL DEFAULT '',
    tags          TEXT             NOT NULL DEFAULT '',
    interval_days INTEGER          NOT NULL DEFAULT 1,
    ease          DOUBLE PRECISION NOT NULL DEFAULT 2.5,
    repetitions   INTEGER          NOT NULL DEFAULT 0,
    due_date      DATE             NOT NULL DEFAULT CURRENT_DATE,
    created_at    TIMESTAMPTZ      NOT NULL DEFAULT now(),
    UNIQUE (deck_id, front)
);

CREATE TABLE study_sessions (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    deck_id    BIGINT      NOT NULL REFERENCES decks(id) ON DELETE CASCADE,
    quiz_mode  TEXT        NOT NULL,
    card_queue JSONB       NOT NULL,
    position   INTEGER     NOT NULL DEFAULT 0,
    correct    INTEGER     NOT NULL DEFAULT 0,
    total      INTEGER     NOT NULL DEFAULT 0,
    started_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    ended_at   TIMESTAMPTZ
);

CREATE INDEX study_sessions_deck ON study_sessions(deck_id);

CREATE TABLE session_answers (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id  BIGINT      NOT NULL REFERENCES study_sessions(id) ON DELETE CASCADE,
    card_id     BIGINT      NOT NULL REFERENCES cards(id) ON DELETE CASCADE,
    correct     BOOLEAN     NOT NULL,
    given       TEXT        NOT NULL DEFAULT '',
    answered_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX session_answers_session ON session_answers(session_id);

CREATE TABLE settings (
    user_id    BIGINT      NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    key        TEXT        NOT NULL,
    value      TEXT        NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (user_id, key)
);

CREATE TABLE llm_providers (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id          BIGINT      NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    name             TEXT        NOT NULL,
    preset           TEXT        NOT NULL,
    base_url         TEXT        NOT NULL DEFAULT '',
    model            TEXT        NOT NULL DEFAULT '',
    api_key          TEXT        NOT NULL DEFAULT '',
    active           BOOLEAN     NOT NULL DEFAULT false,
    disable_thinking BOOLEAN     NOT NULL DEFAULT false,
    created_at       TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX llm_providers_user ON llm_providers(user_id);
-- At most one active provider per user, enforced by the database.
CREATE UNIQUE INDEX llm_providers_active ON llm_providers(user_id) WHERE active;

CREATE TABLE conversations (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT      NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    kind       TEXT        NOT NULL CHECK (kind IN ('tutor', 'deck_builder')),
    card_id    BIGINT      REFERENCES cards(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    -- A tutor conversation is about a card; a deck builder's is not.
    CHECK ((kind = 'tutor') = (card_id IS NOT NULL))
);

CREATE UNIQUE INDEX conversations_tutor ON conversations(user_id, card_id) WHERE kind = 'tutor';
CREATE UNIQUE INDEX conversations_builder ON conversations(user_id) WHERE kind = 'deck_builder';

CREATE TABLE conversation_messages (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conversation_id BIGINT      NOT NULL REFERENCES conversations(id) ON DELETE CASCADE,
    role            TEXT        NOT NULL CHECK (role IN ('user', 'assistant')),
    content         TEXT        NOT NULL DEFAULT '',
    status          TEXT        NOT NULL DEFAULT 'done' CHECK (status IN ('done', 'generating', 'error')),
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX conversation_messages_conversation ON conversation_messages(conversation_id, id);
