package ai

import (
	"context"
	"encoding/json"
	"fmt"
	"log"
	"net/http"
	"net/url"
	"os"
	"strings"
	"time"

	"github.com/ollama/ollama/api"
)

type CardData struct {
	Front   string `json:"front"`
	Back    string `json:"back"`
	Example string `json:"example"`
}

type Client struct {
	client *api.Client
	model  string
}

func NewClient() (*Client, error) {
	host := os.Getenv("OLLAMA_HOST")
	if host == "" {
		host = "http://localhost:11434"
	}
	model := os.Getenv("OLLAMA_MODEL")
	if model == "" {
		model = "llama3"
	}

	base, err := url.Parse(host)
	if err != nil {
		return nil, fmt.Errorf("invalid OLLAMA_HOST %q: %w", host, err)
	}

	ollamaClient := api.NewClient(base, http.DefaultClient)

	if err := healthCheck(ollamaClient); err != nil {
		return nil, fmt.Errorf("ollama unreachable at %s: %w", host, err)
	}

	log.Printf("ai: connected to ollama at %s, model=%s", host, model)

	return &Client{
		client: ollamaClient,
		model:  model,
	}, nil
}

func healthCheck(client *api.Client) error {
	ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
	defer cancel()

	_, err := client.List(ctx)
	return err
}

func (c *Client) GenerateCards(language, promptText string) ([]CardData, error) {
	ctx, cancel := context.WithTimeout(context.Background(), 3*time.Minute)
	defer cancel()

	sp := `You are a flashcard generator for language learning. Given a target language and a topic description, generate a set of flashcards.

Output ONLY valid JSON — an array of objects with these keys:
- "front": the word/phrase in ` + language + `
- "back": the translation in English
- "example": a short example sentence in ` + language + ` using the word/phrase, followed by its English translation in brackets. Format: "Target sentence (English translation)"

Do not include any other text, markdown, or explanation. Just the JSON array.`

	userPrompt := fmt.Sprintf("Target language: %s\nTopic: %s", language, promptText)

	req := &api.ChatRequest{
		Model: c.model,
		Messages: []api.Message{
			{Role: "system", Content: sp},
			{Role: "user", Content: userPrompt},
		},
		Stream: &[]bool{false}[0],
	}

	var fullResponse strings.Builder
	respHandler := func(resp api.ChatResponse) error {
		fullResponse.WriteString(resp.Message.Content)
		return nil
	}

	if err := c.client.Chat(ctx, req, respHandler); err != nil {
		return nil, fmt.Errorf("ollama chat: %w", err)
	}

	return parseCards(fullResponse.String())
}

func parseCards(raw string) ([]CardData, error) {
	cleaned := strings.TrimSpace(raw)
	if strings.HasPrefix(cleaned, "```") {
		idx := strings.Index(cleaned, "\n")
		if idx >= 0 {
			cleaned = cleaned[idx+1:]
		}
		if end := strings.LastIndex(cleaned, "```"); end >= 0 {
			cleaned = cleaned[:end]
		}
		cleaned = strings.TrimSpace(cleaned)
	}

	var cards []CardData
	if err := json.Unmarshal([]byte(cleaned), &cards); err != nil {
		type autoGenerated struct {
			Cards []CardData `json:"cards"`
		}
		var wrapped autoGenerated
		if err2 := json.Unmarshal([]byte(cleaned), &wrapped); err2 == nil && len(wrapped.Cards) > 0 {
			return wrapped.Cards, nil
		}
		return nil, fmt.Errorf("parse cards: %w (raw: %.200s)", err, cleaned)
	}

	return cards, nil
}
