package ai

import (
	"encoding/json"
	"fmt"
	"strings"
)

// systemPrompt returns the flashcard-generation system prompt for language.
func systemPrompt(language string) string {
	return `You are a flashcard generator for language learning. Given a target language and a topic description, generate a set of flashcards.

Output ONLY valid JSON — an array of objects with these keys:
- "front": the word/phrase in ` + language + `
- "back": the translation in English
- "example": a short example sentence in ` + language + ` using the word/phrase, followed by its English translation in brackets. Format: "Target sentence (English translation)"

Do not include any other text, markdown, or explanation. Just the JSON array.`
}

// userPrompt returns "Target language: %s\nTopic: %s".
func userPrompt(language, promptText string) string {
	return fmt.Sprintf("Target language: %s\nTopic: %s", language, promptText)
}

// parseCards strips ``` fences, tries bare array, falls back to {"cards": [...]} wrapper.
func parseCards(raw string) ([]CardData, error) {
	cleaned := strings.TrimSpace(raw)
	if strings.HasPrefix(cleaned, "```") {
		idx := strings.Index(cleaned, "\n")
		if idx >= 0 {
			cleaned = cleaned[idx+1:]
		}
		if end := strings.LastIndex(cleaned, "```"); end >= 0 {
			cleaned = cleaned[:end]
		}
		cleaned = strings.TrimSpace(cleaned)
	}

	var cards []CardData
	if err := json.Unmarshal([]byte(cleaned), &cards); err != nil {
		type autoGenerated struct {
			Cards []CardData `json:"cards"`
		}
		var wrapped autoGenerated
		if err2 := json.Unmarshal([]byte(cleaned), &wrapped); err2 == nil && len(wrapped.Cards) > 0 {
			return wrapped.Cards, nil
		}
		return nil, fmt.Errorf("parse cards: %w (raw: %.200s)", err, cleaned)
	}

	return cards, nil
}
